post/urls.py
from django.urls import path
from .views import create_list_post_comment, like_unlike, DeletePost, UpdatePost

app_name = 'post'

urlpatterns = [
    path('', create_list_post_comment, name='create_list_post_comment'),
    path('liked/', like_unlike, name='like_unlike'),
    path('<pk>/delete', DeletePost.as_view(), name='delete-post'),
    path('<pk>/update', UpdatePost.as_view(), name='update-post'),
]

pp4merosathi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home_page'),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('post/', include('post.urls', namespace='post')),
    path('accounts/', include('allauth.urls')),

]

userprofile/urls.py
from django.urls import path
from .views import (
    profile_page_view,
    request_received_view,
    profiles_list_view,
    request_profiles_list_view,
    UserProfileView,
    ProfileListView,
    send_request,
    unfriend,
    accept_request,
    reject_request,
    cancel_request,
    searchresult,
)


app_name = 'userprofile'

urlpatterns = [
    path('allprofiles/', ProfileListView.as_view(), name='profiles_list_view'),
    path('', profile_page_view, name='profile_page_view'),
    path('request/', request_received_view, name='request_received_view'),
    path('torequest/', request_profiles_list_view, name='request_profiles_list_view'),
    path('send_request/', send_request, name='send_request'),
    path('cancel_request/', cancel_request, name='cancel_request'),
    path('unfriend/', unfriend, name='unfriend'),
    path('request/acceptrequest/', accept_request, name='accept_request'),
    path('request/rejectrequest/', reject_request, name='reject_request'),
    path('searchresult/', searchresult, name='searchresult'),
    path('<slug>/', UserProfileView.as_view(), name='user_profile_view'),
]

userprofile/models.py
from django.db import models
from django.shortcuts import reverse
from django.contrib.auth.models import User
from .utilities import get_random_username_addon
from django.template.defaultfilters import slugify
from cloudinary.models import CloudinaryField
from django.db.models import Q

class ProfileManager(models.Manager):

    def get_all_profiles_to_invite(self, sender):
        profiles = Profile.objects.all().exclude(user=sender)
        profile = Profile.objects.get(user=sender)
        qs = Friendship.objects.filter(Q(sender=profile) | Q(receiver=profile))

        accepted = []
        for fs in qs:
            if fs.status == 'accepted':
                accepted.append(fs.receiver)
                accepted.append(fs.sender)
        
        available = [profile for profile in profiles if profile not in accepted]
        return available

    def get_all_profile(self, me):
        profiles = Profile.objects.all().exclude(user=me)
        return profiles



class Profile(models.Model):
    first_name = models.CharField(max_length=200, blank=True)
    last_name = models.CharField(max_length=200, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(default="No Bio...", max_length=300)
    email = models.EmailField(max_length=200, blank=True)
    country = models.CharField(max_length=200, blank=True)
    avatar = CloudinaryField('image', default='blank-avatar_pxjsla.png')
    friends = models.ManyToManyField(User, blank=True, related_name='friends')
    slug = models.SlugField(unique=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ProfileManager()

    def __str__(self):
        return f"{self.user.username}"
        # -{self.created.strftime('%d-%m-%Y')}

    def get_absolute_url(self):
        return reverse('userprofile:user_profile_view', kwargs={'slug': self.slug})

    def friends_list(self):
        return self.friends.all()

    def total_friends(self):
        return self.friends.all().count()

    def total_posts(self):
        return self.posts.all().count()

    def get_all_post(self):
        return self.posts.all()

    def total_likes_given(self):
        likes = self.like_set.all()
        total_likes = 0
        for item in likes:
            if item.value == 'Like':
                total_likes += 1
        return total_likes

    def total_likes_received(self):
        posts = self.posts.all()
        total_likes = 0
        for item in posts:
            total_likes += item.liked.all().count()
        return total_likes


    __initial_first_name = None
    __initial_last_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__initial_first_name = self.first_name
        self.__initial_last_name = self.last_name

    def save(self, *args, **kwargs):
        temp_slug = False
        to_slug = self.slug
        if self.first_name != self.__initial_first_name or self.last_name != self.__initial_last_name or self.slug == '':
            if self.first_name and self.last_name:
                to_slug = slugify(str(self.first_name) + " " + str(self.last_name))
                temp_slug = Profile.objects.filter(slug=to_slug).exists()
                while temp_slug:
                    to_slug = slugify(to_slug + " " + str(get_random_username_addon()))
                    temp_slug = Profile.objects.filter(slug=to_slug).exists()
            else:
                to_slug = str(self.user)
        self.slug = to_slug
        super().save(*args, **kwargs)

STATUS_CHOICES = (
    ('send', 'send'),
    ('accepted', 'accepted')
)

class FriendshipManager(models.Manager):
    def request_received(self, receiver):
        request_list = Friendship.objects.filter(receiver=receiver, status='send')
        return request_list

    def request_send(self, sender):
        all_profiles = Friendship.objects.filter(sender=sender, status='send')
        return all_profiles

class Friendship(models.Model):
    sender = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='receiver')
    status = models. CharField(max_length=8, choices=STATUS_CHOICES)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = FriendshipManager()

    def __str__(self):
        return f"{self.sender}-{self.receiver}-{self.status}"

userprofile/forms.py
from django import forms
from .models import Profile

class ProfileModelForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'bio', 'avatar',)

userprofile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Profile, Friendship
from post.models import Post
from .forms import ProfileModelForm
from django.views.generic import ListView, DetailView
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin



@login_required
def profile_page_view(request):
    user = Profile.objects.get(user=request.user)
    form = ProfileModelForm(request.POST or None, request.FILES or None, instance=user)
    confirm = False
    posts = Post.objects.all().filter(author=user)
    len_posts = True if len(Post.objects.all().filter(author=user)) > 0 else False

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            confirm = True

    context = {
        'user': user,
        'form': form,
        'confirm': confirm,
        'posts': posts,
        'len_posts': len_posts,
    }

    return render(request, 'userprofile/profilepage.html', context)


@login_required
def request_received_view(request):
    user = Profile.objects.get(user=request.user)
    request_list = Friendship.objects.request_received(user)
    result = list(map(lambda x: x.sender, request_list))
    is_empty = False
    if len(result) == 0:
        is_empty = True

    context = {'request_list': result, 'is_empty': is_empty, }

    return render(request, 'userprofile/request.html', context)


@login_required
def accept_request(request):
    if request.method=='POST':
        pk = request.POST.get('request_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        req = get_object_or_404(Friendship, sender=sender, receiver=receiver)
        if req.status == 'send':
            req.status = 'accepted'
            req.save()
    
    return redirect('userprofile:request_received_view')


@login_required
def reject_request(request):
    if request.method=='POST':
        pk = request.POST.get('request_pk')
        sender = Profile.objects.get(pk=pk)
        receiver = Profile.objects.get(user=request.user)
        req = get_object_or_404(Friendship, sender=sender, receiver=receiver)
        req.delete()

    return redirect('userprofile:request_received_view')


@login_required
def request_profiles_list_view(request):
    user = Profile.objects.get(user=request.user)
    all_profiles = Friendship.objects.request_send(user)
    result = list(map(lambda x: x.receiver, all_profiles))
    is_empty = False
    if len(result) == 0:
        is_empty = True

    context = {'all_profiles': result, 'is_empty': is_empty, }

    return render(request, 'userprofile/torequest.html', context)


@login_required
def profiles_list_view(request):
    user = request.user
    all_profiles = Profile.objects.get_all_profile(user)

    context = {'all_profiles': all_profiles}

    return render(request, 'userprofile/allprofiles.html', context)


class UserProfileView (LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'userprofile/userdetail.html'

    def get_object(self):
        slug = self.kwargs.get('slug')
        profile = Profile.objects.get(slug=slug)
        return profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username=self.request.user)
        profile = Profile.objects.get(user=user)
        req_r = Friendship.objects.filter(sender=profile)
        req_s = Friendship.objects.filter(receiver=profile)
        req_receiver = []
        req_sender = []
        for item in req_r:
            req_receiver.append(item.receiver.user)
        for item in req_s:
            req_sender.append(item.sender.user)
        context['req_receiver'] = req_receiver
        context['req_sender'] = req_sender
        context['posts'] = self.get_object().get_all_post()
        context['len_posts'] = True if len(self.get_object().get_all_post()) > 0 else False

        return context


class ProfileListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = 'userprofile/allprofiles.html'
    context_object_name = 'all_profiles'

    def get_queryset(self):
        all_profiles = Profile.objects.get_all_profile(self.request.user)
        return all_profiles

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = User.objects.get(username=self.request.user)
        profile = Profile.objects.get(user=user)
        req_r = Friendship.objects.filter(sender=profile)
        req_s = Friendship.objects.filter(receiver=profile)
        req_receiver = []
        req_sender = []
        for item in req_r:
            req_receiver.append(item.receiver.user)
        for item in req_s:
            req_sender.append(item.sender.user)
        context['req_receiver'] = req_receiver
        context['req_sender'] = req_sender
        context['is_empty'] = False
        if len(self.get_queryset()) == 0:
            context['is_empty'] = True

        return context

@login_required
def send_request(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        fs = Friendship.objects.create(sender=sender, receiver=receiver, status='send')

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('userprofile:profile_page_view')

@login_required
def cancel_request(request):
    if request.method == 'POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        fs = Friendship.objects.get(sender=sender, receiver=receiver, status='send')
        fs.delete()

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('userprofile:request_profiles_list_view')

@login_required
def unfriend(request):
    if request.method=='POST':
        pk = request.POST.get('profile_pk')
        user = request.user
        sender = Profile.objects.get(user=user)
        receiver = Profile.objects.get(pk=pk)

        fs = Friendship.objects.get(
            (Q(sender=sender) & Q(receiver=receiver)) | (Q(sender=receiver) & Q(receiver=sender))
            )
        fs.delete()

        return redirect(request.META.get('HTTP_REFERER'))
    return redirect('userprofile:profile_page_view')

@login_required
def searchresult(request):
    if request.method == 'POST':
        result = request.POST['search']
        result_profile = Profile.objects.all().filter(Q(first_name__icontains=result) | Q(last_name__icontains=result))
        context = {
            'result': result,
            'result_profile': result_profile
        }
        return render(request, 'userprofile/searchresult.html', context)
    else:
        return render(request, 'userprofile/searchresult.html', {})

userprofile/templates/userprofile/allprofiles.html
{% extends 'base.html' %}

{% block title %}
Profile List
{% endblock title %}

{% block content %}
{% if is_empty %}
No Other profile exist
{% endif %}


{% for profile in all_profiles %}
{% if profile.user not in req_receiver and profile.user not in req_sender %}
<div class="ui segment">
    <div class="ui grid">
        <div class="ui row stackable">
            <div class="four wide column">
                <img src="{{ profile.avatar.url }}" alt="" class="ui rounded fluid image">
            </div>
            <div class="twelve wide column">
                <h3>{{ profile.first_name }} {{ profile.last_name }}</h3>
                <p>{{ profile.bio }}</p>
                <a href="{{ profile.get_absolute_url }}">
                    <button class="ui primary button mb-5 bwide-big">View Profile</button>
                </a>
                <br>

                <form action="{% url 'userprofile:send_request' %}" method="POST">
                    {% csrf_token %}
                    <input type="hidden" name="profile_pk" value="{{ profile.pk }}">
                    <button type="submit" class="ui positive basic button bwide-big"><i
                            class="plus square icon"></i>Add as Friend</button>
                </form>

                <!-- {% if profile.user in req_receiver and request.user not in profile.friends.all %}
                    <button class="ui disabled button bwide-big"><i class="user icon"></i>Friend
                        Request sent</button>
                    {% endif %}

                    {% if request.user in profile.friends.all %}
                        <form action="{% url 'userprofile:unfriend' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{ profile.pk }}">
                            <button type="submit" class="ui negative basic button bwide-big"><i
                                    class="minus square icon"></i>Remove as Friend</button>
                        </form>
                    {% endif %} -->
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}


{% endblock content %}

userprofile/templates/userprofile/profilepage.html
{% extends 'base.html' %}

{% block title %}
{{user.first_name}}'s Profile
{% endblock title %}

{% block content %}

<!-- Modal to update user profile -->
<div class="ui modal" id="up-modal">
    <i class="close icon"></i>
    <div class="header">
        Update your Profile Information
    </div>
    <div class="image content">
        <div class="ui medium image">
            <img src="{{user.avatar.url}}">
        </div>
        <div class="description">
            <div class="ui header">Please provide the information you want to update.</div>
            <!-- form to update user profile information -->
            <form action="" method="post" class="ui form" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
        </div>
    </div>
    <div class="actions">
        <button class="ui positive right labeled icon button">
            Update
            <i class="checkmark icon"></i>
        </button>
        </form>
    </div>
</div>

{% if confirm %}
<div class="ui blue message">Thank you for updating your profile information.</div>
{% endif %}
<div class="ui grid">
    <div class="ui row stackable">
        <div class="four wide column">
            <img src="{{user.avatar.url}}" alt="" class="ui centered medium rounded image">
            <h1>{{user.first_name}} {{ user.last_name}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ user.total_posts }}</div>
                </div>
                <div class="item">
                    Likes Given
                    <div class="ui label">{{ user.total_likes_given }}</div>
                </div>
                <div class="item">
                    Likes Received
                    <div class="ui label">{{ user.total_likes_received }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ user.total_friends }}</div>
                </div>
            </div>
            <button class="ui active button mt-5" id="update-profile">Update Profile</button>
        </div>
        <div class="twelve wide column">
            {% if len_posts %}
            {% for post in posts %}
            <div class="segment ui fluid">
                {% if post.image.url %}
                <img alt class="image w-100" src="{{ post.image.url }}">
                {% endif %}
                {{ post.content }}
            </div>
            {% endfor %}
            {% else %}
            <h1>No post from the {{object.first_name}}</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content%}

userprofile/templates/userprofile/profilepage_.html
{% extends 'base.html' %}

{% block title %}
{{ user.first_name }} Profile Page
{% endblock title %}

{% block content %}

<!-- Modal to update user profile -->
<div class="ui modal">
    <i class="close icon"></i>
    <div class="header">
        Update your Profile Information
    </div>
    <div class="image content">
        <div class="ui medium image">
            <img src="{{user.avatar.url}}">
        </div>
        <div class="description">
            <div class="ui header">Please provide the information you want to update.</div>
            <!-- form to update user profile information -->
            <form action="" method="post" class="ui form" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
        </div>
    </div>
    <div class="actions">
        <button class="ui positive right labeled icon button">
            Update
            <i class="checkmark icon"></i>
        </button>
        </form>
    </div>
</div>


<div class="ui segment">
    {% if confirm %}
        <div class="ui blue message">Thank you for updating your profile information.</div>
    {% endif %}
    <h3>Welcome {{ user.first_name }}</h3>
    <div class="ui grid">
        <div class="row">
            <div class="six wide column">
                <img class="ui medium rounded image" src="{{ user.avatar.url}}"></img>
                <button class="ui active button mt-5" id="update-profile">Update Profile</button>
            </div>
            <div class="ten wide column">
                <table class="ui table">
                    <tbody>
                        <tr>
                            <td>Username</td>
                            <td>{{ user.user }}</td>
                        </tr>
                        <tr>
                            <td>First Name</td>
                            <td>{{ user.first_name }}</td>
                        </tr>
                        <tr>
                            <td>Last Name</td>
                            <td>{{ user.last_name }}</td>
                        </tr>
                        <tr>
                            <td>User Bio</td>
                            <td>{{ user.bio }}</td>
                        </tr>
                        <tr>
                            <td>Friends</td>
                            <td>{{ user.total_friends }}</td>
                        </tr>
                        <tr>
                            <td>Friends</td>
                            <td>
                                <ul>
                                    {% for friend in user.friends_list %}
                                        <li>{{ friend }}</li>
                                    {% endfor %}
                                </ul>
                            </td>
                        </tr>
                        <tr>
                            <td>Posts</td>
                            <td>{{ user.total_posts }}</td>
                        </tr>
                        <tr>
                            <td>Likes Given</td>
                            <td>{{ user.total_likes_given }}</td>
                        </tr>
                        <tr>
                            <td>Likes Received</td>
                            <td>{{ user.total_likes_received }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

userprofile/templates/userprofile/request.html
{% extends 'base.html' %}

{% block title %}
Requests
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No Invitation here..</h1>
    {% endif %}
    
    {% for request in request_list %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="ui row stackable">
                    <div class="four wide column">
                        <img src="{{ request.avatar.url }}" alt="" class="ui rounded fluid image">
                        <a href="{{ request.get_absolute_url }}">
                            <button class="ui primary button mt-5 fluid">View Profile</button>
                        </a>
                    </div>
                    <div class="twelve wide column">
                        <h3>{{ request.first_name }} {{ request.last_name }}</h3>
                        <p>{{ request.bio }}</p>
                        <br>
                        <div class="meta">{{ request.first_name }} wants to Add you as friend?</div>
                        <form action="{% url 'userprofile:accept_request' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="request_pk" value="{{ request.pk }}">
                            <button type="submit" class="ui positive basic button mt-5 bwide-big"><i
                                    class="check square icon"></i>Accept Request</button>
                        </form>
                        
                        <form action="{% url 'userprofile:reject_request' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="request_pk" value="{{ request.pk }}">
                            <button type="submit" class="ui negative basic button mt-5 bwide-big"><i
                                    class="close square icon"></i>Reject Request</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    
{% endblock content %}

userprofile/templates/userprofile/searchresult.html
{% extends 'base.html' %}

{% block title %}
Profile List
{% endblock title %}

{% block content %}
<h1>Test searchreasult page</h1>

{% if result %}
{% if result_profile %}
    {% for profile in result_profile %}
    <div class="ui segment">
        <div class="ui grid">
            <div class="row">
                <div class="four wide column">
                    <img src="{{ profile.avatar.url }}" alt="" class="ui rounded fluid image">
                </div>
                <div class="twelve wide column">
                    <h3>{{ profile.first_name }} {{ profile.last_name }}</h3>
                    <p>{{ profile.bio }}</p>
                    <a href="{{ profile.get_absolute_url }}">
                        <button class="ui primary button mb-5 bwide-big">View Profile</button>
                    </a>
    
                    <!-- <form action="{% url 'userprofile:send_request' %}" method="POST">
                        {% csrf_token %}
                        <input type="hidden" name="profile_pk" value="{{ profile.pk }}">
                        <button type="submit" class="ui positive basic button bwide-big"><i
                                class="plus square icon"></i>Add as Friend</button>
                    </form>
    
                    {% if profile.user in req_receiver and request.user not in profile.friends.all %}
                        <button class="ui disabled button bwide-big"><i class="user icon"></i>Friend
                            Request sent</button>
                        {% endif %}
    
                        {% if request.user in profile.friends.all %}
                            <form action="{% url 'userprofile:unfriend' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="profile_pk" value="{{ profile.pk }}">
                                <button type="submit" class="ui negative basic button bwide-big"><i
                                        class="minus square icon"></i>Remove as Friend</button>
                            </form>
                        {% endif %} -->
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
{% else %}
    <h3>No Matching result found.</h3>
{% endif %}
{% else%}
    <h3>you searched for nothing</h3>
{% endif %}
{% endblock content %}

userprofile/templates/userprofile/torequest.html
{% extends 'base.html' %}

{% block title %}
Send Requests
{% endblock title %}

{% block content %}
    {% if is_empty %}
        <h1>No Invitation Send..</h1>
    {% endif %}
    
    {% for profile in all_profiles %}
        <div class="ui segment">
            <div class="ui grid">
                <div class="ui row stackable">
                    <div class="four wide column">
                        <img src="{{ profile.avatar.url }}" alt="" class="ui rounded fluid image">
                        <a href="{{ profile.get_absolute_url }}">
                            <button class="ui primary button mt-5 fluid">View Profile</button>
                        </a>
                    </div>
                    <div class="twelve wide column">
                        <h3>{{ profile.first_name }} {{ profile.last_name }}</h3>
                        <p>{{ profile.bio }}</p>
                        <br>
                        <div class="meta">You have send friend Request to {{ profile.first_name }}</div>
                            <button class="ui disabled button bwide-big">
                                <i class="user icon"></i>Friend Request sent
                            </button>
                        
                        <form action="{% url 'userprofile:cancel_request' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value="{{ profile.pk }}">
                            <button type="submit" class="ui negative basic button mt-5 bwide-big"><i
                                    class="close square icon"></i>Cancel Friend Request</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    
{% endblock content %}

userprofile/templates/userprofile/userdetail.html
{% extends 'base.html' %}

{% block title %}
{{object.first_name}}'s Profile
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="ui row stackable">
        <div class="four wide column">
            <img src="{{object.avatar.url}}" alt="" class="ui centered medium rounded image">
            <h1>{{object.first_name}} {{ object.last_name}}</h1>
            <div class="ui vertical fluid menu">
                <div class="item">
                    Posts
                    <div class="ui label">{{ object.total_posts }}</div>
                </div>
                <div class="item">
                    Likes Given
                    <div class="ui label">{{ object.total_likes_given }}</div>
                </div>
                <div class="item">
                    Likes Received
                    <div class="ui label">{{ object.total_likes_received }}</div>
                </div>
                <div class="item">
                    Friends
                    <div class="ui label">{{ object.total_friends }}</div>
                </div>
            </div>
            {% if object.user not in req_receiver and object.user not in req_sender %}
            <form action="{% url 'userprofile:send_request' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{ object.pk }}">
                <button type="submit" class="ui positive basic button w-100"><i
                        class="plus square icon"></i>Add as Friend</button>
            </form>
            {% endif %}

            {% if object.user in req_receiver and request.user not in object.friends.all %}
            <button class="ui disabled button w-100"><i class="user icon"></i>Friend
                Request sent</button>
            {% endif %}

            {% if request.user in object.friends.all %}
            <form action="{% url 'userprofile:unfriend' %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="profile_pk" value="{{ object.pk }}">
                <button type="submit" class="ui negative basic button w-100"><i
                        class="minus square icon"></i>Remove as Friend</button>
            </form>
            {% endif %}
        </div>
        <div class="twelve wide column">
            {% if len_posts %}
            {% for post in posts %}
            <div class="segment ui fluid">
                {% if post.image.url %}
                <img alt class="image w-100" src="{{ post.image.url }}">
                {% endif %}
                {{ post.content }}
            </div>
            {% endfor %}
            {% else %}
            <h1>No post from the {{object.first_name}}</h1>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content%}