post/urls.py
from django.urls import path
from .views import create_list_post_comment, like_unlike, DeletePost, UpdatePost

app_name = 'post'

urlpatterns = [
    path('', create_list_post_comment, name='create_list_post_comment'),
    path('liked/', like_unlike, name='like_unlike'),
    path('<pk>/delete', DeletePost.as_view(), name='delete-post'),
    path('<pk>/update', UpdatePost.as_view(), name='update-post'),
]

pp4merosathi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home_page'),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('post/', include('post.urls', namespace='post')),
    path('accounts/', include('allauth.urls')),

]

userprofile/urls.py
from django.urls import path
from .views import (
    profile_page_view,
    request_received_view,
    profiles_list_view,
    request_profiles_list_view,
    UserProfileView,
    ProfileListView,
    send_request,
    unfriend,
    accept_request,
    reject_request,
    cancel_request,
    searchresult,
)


app_name = 'userprofile'

urlpatterns = [
    path('allprofiles/', ProfileListView.as_view(), name='profiles_list_view'),
    path('', profile_page_view, name='profile_page_view'),
    path('request/', request_received_view, name='request_received_view'),
    path('torequest/', request_profiles_list_view, name='request_profiles_list_view'),
    path('send_request/', send_request, name='send_request'),
    path('cancel_request/', cancel_request, name='cancel_request'),
    path('unfriend/', unfriend, name='unfriend'),
    path('request/acceptrequest/', accept_request, name='accept_request'),
    path('request/rejectrequest/', reject_request, name='reject_request'),
    path('searchresult/', searchresult, name='searchresult'),
    path('<slug>/', UserProfileView.as_view(), name='user_profile_view'),
]

templates/main/navbar.html
{% url 'post:create_list_post_comment' as path_to_post %}
{% url 'userprofile:profile_page_view' as path_to_userprofile %}
{% url 'userprofile:profiles_list_view' as path_to_allprofile %}
{% url 'userprofile:request_profiles_list_view' as path_to_addfriend %}
{% url 'userprofile:request_received_view' as path_to_acceptfriend %}
{% url 'userprofile:searchresult' as path_to_searchresult %}


<div class="ui fixed inverted menu nav mb-7">
    <div class="ui container">
        <div class="item">
            <a href="{{ path_to_post }}"
                class="{% if request.path == path_to_home %} active {% endif %}">
                <div class="f-screen">
                    <h3>Merosathi</h3>
                </div>
                <div class="s-screen">
                    <h4>Merosathi</h4>
                </div>
            </a>
        </div>
        <div class="right menu">
            <div class="item">
                <form action="{% url 'userprofile:searchresult' %}" method="POST"
                    class="f-screen">
                    {% csrf_token %}
                    <div class="ui action left icon input">
                        <input class="prompt" type="text" name='search'
                            placeholder="name of a friend...">
                        <i class="search icon"></i>
                        <button type='submit' class="ui button">Search</button>
                    </div>
                </form>
                <div class="ui teal buttons s-screen">
                    <div class="ui floating dropdown icon button s-screen">
                        <i class="fa-solid fa-magnifying-glass"></i>
                        <div class="menu m-search">
                            <form action="{% url 'userprofile:searchresult' %}" method="POST"
                                class="s-screen item">
                                {% csrf_token %}
                                <div class="ui icon search input">
                                    <input class="prompt" type="text" name='search'
                                        placeholder="name of a friend..." autofocus="autofocus">
                                    <i class="search icon"></i>
                                    <!-- <button type='submit' class="ui button">Search</button> -->
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ui teal buttons">
                    <div class="ui button f-screen">Friends</div>
                    <div class="ui floating dropdown icon button">
                        <i class="dropdown icon f-screen"></i>
                        <i class="fa-solid fa-user-group s-screen"></i>
                        <div class="menu">
                            <a href="{{ path_to_allprofile }}"
                                class="{% if request.path == path_to_allprofile %} active {% endif %} item">
                                All Profiles
                            </a>
                            <a href="{{ path_to_addfriend }}"
                                class="{% if request.path == path_to_addfriend %} active {% endif %} item">
                                Add Friends&nbsp;
                                <div class="ui purple horizontal label">{{ request_send_num }}
                                </div>
                            </a>
                            <a href="{{ path_to_acceptfriend }}"
                                class="{% if request.path == path_to_acceptfriend %} active {% endif %} item">
                                Friends Request Received&nbsp;
                                <div class="ui purple horizontal label">{{ request_rec_num }}
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <a href="{{ path_to_userprofile }}"
                class="{% if request.path == path_to_userprofile %} active {% endif %} item">
                <img src="{{ picture.url }}" alt="" class="ui avatar image">&nbsp;
                <div class="f-screen">{{ request.user }}</div>
            </a>
            <a href="{% url 'account_logout' %}" class="ui item computer only" id="sign-out">
                <div class="f-screen">Logout</div>
                <div class="s-screen"><i class="fa-solid fa-right-from-bracket"></i></div>
            </a>
        </div>
    </div>
</div>