post/urls.py
from django.urls import path
from .views import create_list_post_comment, like_unlike, DeletePost, UpdatePost

app_name = 'post'

urlpatterns = [
    path('', create_list_post_comment, name='create_list_post_comment'),
    path('liked/', like_unlike, name='like_unlike'),
    path('<pk>/delete', DeletePost.as_view(), name='delete-post'),
    path('<pk>/update', UpdatePost.as_view(), name='update-post'),
]

pp4merosathi/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import home_page

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_page, name='home_page'),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('post/', include('post.urls', namespace='post')),
    path('accounts/', include('allauth.urls')),

]

post/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from django.core.validators import FileExtensionValidator
from userprofile.models import Profile


class Post(models.Model):
    content = models.TextField()
    image = CloudinaryField('image', blank=True)
    liked = models.ManyToManyField(Profile, blank=True, related_name='likes')
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='posts')

    def __str__(self):
        return str(self.content[:20])

    def total_likes(self):
        return self.liked.all().count()

    def number_comments(self):
        return self.comment_set.all().count()

    class Meta:
        ordering = ('-created_on',)


class Comment(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField(max_length=300)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk)


LIKE_CHOICES = (
    ('Like', 'Like'),
    ('Unlike', 'Unlike'),
)


class Like(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    updated_on = models.DateTimeField(auto_now=True)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}-{self.post}-{self.value}"

post/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.Textarea(attrs={'rows': 3, 'placeholder': 'Whats on your mind?'}))

    class Meta:
        model = Post
        fields = ('content', 'image')


class CommentForm(forms.ModelForm):
    body = forms.CharField(label='', widget=forms.TextInput(attrs={'placeholder': 'Add a comment...'}))

    class Meta:
        model = Comment
        fields = ('body',)

post/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from .models import Post, Like
from userprofile.models import Profile
from .forms import PostForm, CommentForm
from django.views.generic import UpdateView, DeleteView
from django.contrib import messages
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# View to Create Post, comment post and like post
@login_required
def create_list_post_comment(request):
    post_content = Post.objects.all()
    profile = Profile.objects.get(user=request.user)


# form for posting and commenting
    post_form = PostForm()
    comment_form = CommentForm()
    posted = False

    profile = Profile.objects.get(user=request.user)

    if 'post_submit' in request.POST:
        print(request.POST)
        post_form = PostForm(request.POST, request.FILES)
        if post_form.is_valid():
            instance = post_form.save(commit=False)
            instance.author = profile
            instance.save()
            post_form = PostForm()
            posted = True

    if 'comment_submit' in request.POST:
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            instance = comment_form.save(commit=False)
            instance.user = profile
            instance.post = Post.objects.get(id=request.POST.get('post_id'))
            instance.save()
            comment_form = CommentForm()

    context = {
        'post_content': post_content,
        'profile': profile,
        'post_form': post_form,
        'comment_form': comment_form,
        'posted': posted,
    }

    return render(request, 'post/main.html', context)

@login_required
def like_unlike(request):
    user = request.user
    if request.method == 'POST':
        post_id = request.POST.get('post_id')
        post_obj = Post.objects.get(id=post_id)
        profile = Profile.objects.get(user=user)

        if profile in post_obj.liked.all():
            post_obj.liked.remove(profile)
        else:
            post_obj.liked.add(profile)

        like, created = Like.objects.get_or_create(user=profile, post_id=post_id)

        if not created:
            if like.value == 'Like':
                like.value = 'Unlike'
            else:
                like.value = 'Like'
        else:
            like.value = 'Like'

            post_obj.save()
            like.save()

        data = {
            'value': like.value,
            'likes': post_obj.liked.all().count()
        }
        return JsonResponse(data, safe=False)

    return redirect('post:create_list_post_comment')


class DeletePost(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'post/delete.html'
    success_url = reverse_lazy('post:create_list_post_comment')

    def get_object(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        obj = Post.objects.get(pk=pk)
        if not obj.author.user == self.request.user:
            messages.warning(self.requeset, 'You are not author of the post')
        return obj


class UpdatePost(LoginRequiredMixin, UpdateView):
    form_class = PostForm
    model = Post
    template_name = 'post/update.html'
    success_url = reverse_lazy('post:create_list_post_comment')

    def form_valid(self, form):
        profile = Profile.objects.get(user=self.request.user)
        if form.instance.author == profile:
            return super().form_valid(form)
        else:
            form.add_error(None, 'You are not author of the post')
            return super().form_invalid(form)

# @login_required
# def user_post(request):
#     user = request.author.user
#     user_all_post = Post.objects.all().filter(author=user)

#     return user_all_post

post/templates/post/delete.html
{% extends 'base.html'%}


{% block title %}
Delete Post
{% endblock title %}


{% block content %}
    {% if messages %}
        {% for message in messages %}
            {% if 'warning' in message.tags %}
                <div class="ui megative message">
                    <div class="header">
                        {{ message }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}

    {% if not messages %}
        <div class="ui segment">
            <h3>Delete post?</h3>
                <p>Are you sure you want to delete the post?</p>
                <form action="" method="POST">
                    {% csrf_token %}
                    <button type="submit">Delete</button>
                </form>
        </div>
    {% endif %}
{% endblock content %}

post/templates/post/main.html
{% extends 'base.html' %}

{% block title %}
Posts
{% endblock title %}


{% block content %}
<div class="ui stackable grid">
    <div class="sixteen wide tablet five wide computer column">
        <div class="ui raised segment">
            <form action="" method="POST" class="ui form" enctype="multipart/form-data">
                {% csrf_token %}
                {{post_form}}
                <button type="submit" class="ui button positive mt-5" name="post_submit">Publish</button>
            </form>
        </div>
    </div>
    <div class="sixteen wide tablet eleven wide computer column">
        
        {% for post in post_content %}
        <div class="ui card w-100">
            <div class="content p-5">
                <div class="right floated meta">
                    {% ifequal request.user post.author.user %}
                    <a href="{% url 'post:update-post' post.pk %}">
                        <button class="ui button bwhite-lg"><i class="edit icon"></i></button>
                    </a>
                    <a href="{% url 'post:delete-post' post.pk %}">
                        <button class="ui button bwhite-lg"><i class="trash icon"></i></button>
                    </a>
                    {% endifequal%}
                </div>
                <div class="ui comments">
                    <div class="comment">
                        <div class="ui avatar image">
                            <img src="{{post.author.avatar.url}}">
                        </div>
                        <div class="content">
                            <div>
                                <a class="author">&nbsp;&nbsp;{{ post.author.first_name }}</a>
                            </div>
                            <div class="metadata">
                                <span class="date">{{ post.created_on|timesince}} ago</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                {% if post.image.url %}
                <img alt class="ui big image mb-7" src="{{ post.image.url }}">
                {% endif %}
                <p>{{ post.content }}</p>
            </div>
            <div class="content">
                <div class="right floated">
                    <form action="{% url 'post:like_unlike' %}" method="post" class="like-form"
                        id="{{ post.id }}">
                        {% csrf_token %}
                        <input type="hidden" name="post_id" value="{{post.id}}">
                        <button class="ui button bwhite-lg" type="submit">
                            {% if profile not in post.liked.all %}
                            <i class="heart like icon like-btn{{post.id}}"></i>
                            {% else %}
                            <i class="heart like icon like-btn{{post.id}} blue"></i>
                            {% endif %}
                            <span class="like-counter{{post.id}}">{{ post.total_likes }}</span> likes
                        </button>
                    </form>
                </div>
                {% if post.comment_set.all %}
                <div class="ui fluid accordion">
                    <div class="title">
                        <i class="comment icon"></i>
                        {{ post.number_comments}} comments
                    </div>
                    <div class="content">
                        <div class="ui comments">
                            {% for comment in post.comment_set.all %}
                            <div class="ui comment segment transition raised p-5">
                                <div class="avatar">
                                    <img class="ui avatar" src="{{comment.user.avatar.url}}">
                                </div>
                                <div class="content">
                                    <a class="author">{{ comment.user.first_name }}</a>
                                    <div class="metadata">
                                        <span class="date">{{ comment.created_on|timesince}} ago</span>
                                    </div>
                                    <div class="text">
                                        {{ comment.body }}
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                {% else %}
                <div class="title">
                    <i class="comment icon"></i>
                    No comment yet
                </div>
                {% endif %}
            </div>
            <div class="extra content">
                <form action="" method="post" class="ui form">
                    {% csrf_token %}
                    <div class="right floated meta">
                        <button type="submit" class="ui button primary"
                            name="comment_submit">Comment</button>
                    </div>
                    <input type="hidden" name="post_id" value="{{post.id}}">
                    <div class="ui large transparent left icon input fluid">
                        <i class="heart outline icon"></i>
                        {{ comment_form }}
                    </div>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content %}

post/templates/post/update.html
{% extends 'base.html'%}

{% block title %}
Update Post
{% endblock title %}

{% block content %}
<div class="ui segment">
    <h3>Update Post</h3>
    <form action="" method="POST" class="ui form" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="ui button primary mt-5">
            Update
        </button>
    </form>
</div>
{% endblock content %}